### ISSUE TITLE
Auto mode

### ISSUE THREAD

**Issue by AlfredG92** [lvanderree/com.synplyworks.spider#1]
Ik heb een Gateway aangeschaft voor de remote control van mijn CVE-S. Alleen als ik hem op auto zet in Homey, gaat hij in de gateway naar Boost 10. Kan dit een foutje in de app zijn? Alvast bedankt voor de genomen moeite.

**Comment by lvanderree** [comment]
Ik denk niet dat die fout in mijn code zit, maar ken zelf de auto modus niet, aangezien mijn fan die optie niet heeft (geen meet sensor). Ik heb de optie uit code van itho zelf gehaald, dus weet dat de optie er in zit, maar mijn spiders bieden zelf dus ook geen auto optie en ik heb hem zelf dus ook nooit gebruikt. Als ik het probeer, dan blijft mijn ventilator in de gelijke stand staan. 

In mijn code zie ik (bevestigend:) "what you see is what you get", oftewel de naam "Auto" optie leidt tot de waarde "Auto" : 
https://github.com/lvanderree/com.synplyworks.spider/blob/8585f6d6ba65749d1b9817f9cdec9df9241bc06e/app.json#L79

Bij wijzigen van de ventilator snelheid via de dropdown wordt de volgende code uitgevoerd, waar verder geen verwerking van de waarde wordt toegepast : 

https://github.com/lvanderree/com.synplyworks.spider/blob/8585f6d6ba65749d1b9817f9cdec9df9241bc06e/drivers/fan/device.js#L30

https://github.com/lvanderree/com.synplyworks.spider/blob/8585f6d6ba65749d1b9817f9cdec9df9241bc06e/drivers/fan/device.js#L37

https://github.com/lvanderree/com.synplyworks.spider/blob/8585f6d6ba65749d1b9817f9cdec9df9241bc06e/src/clientManager.ts#L91
(waarin de waarde nog een keer geforceerd naar Uppercase-first-letter wordt) 

Dit wordt ook in console gelogd. 

De client en clientmanager in src draaien ook zonder homey via node mocht je daar ervaren in zijn.

**Comment by AlfredG92** [comment]
Hoi Leon,
  
  
   
  
  
   Bedankt voor je mail. Mijn kennis van Homey is niet zo ver toereikend.
  
  
   Kunnen we eventueel samen naar een oplossing zoeken voor de betreffende auto functie?
  
  
   Het valt me op dat als ik hem nu op auto zet, hij in zowel de Homey app als de Spider app op Boost 10 komt te staan.
  
  
   
  
  
   Hoor graag zodat we mogelijk samen tot een oplossing kunnen komen.
  
  
   
  
  
   Alvast bedankt voor de genomen moeite.
  
  
   
  
  
   Met vr. Groet,
  
  
   
  
  
   Alfred Grovenstein
  
  
   
    Op 5 maart 2020 19:53 schreef Leon van der Ree <notifications@github.com>:
   
   
    
   
   
    
   
   Ik denk niet dat die fout in mijn code zit, maar ken zelf de auto modus niet, aangezien mijn fan die optie niet heeft (geen meet sensor). Ik heb de optie uit code van itho zelf gehaald, dus weet dat de optie er in zit, maar mijn spiders bieden zelf dus ook geen auto optie en ik heb hem zelf dus ook nooit gebruikt. Als ik het probeer, dan blijft mijn ventilator in de gelijke stand staan.
   In mijn code zie ik (bevestigend:) "what you see is what you get", oftewel de naam "Auto" optie leidt tot de waarde "Auto" :https://github.com/lvanderree/com.synplyworks.spider/blob/8585f6d6ba65749d1b9817f9cdec9df9241bc06e/app.json#L79
   Bij wijzigen van de ventilator snelheid via de dropdown wordt de volgende code uitgevoerd, waar verder geen verwerking van de waarde wordt toegepast :
   https://github.com/lvanderree/com.synplyworks.spider/blob/8585f6d6ba65749d1b9817f9cdec9df9241bc06e/drivers/fan/device.js#L30
   https://github.com/lvanderree/com.synplyworks.spider/blob/8585f6d6ba65749d1b9817f9cdec9df9241bc06e/drivers/fan/device.js#L37
   https://github.com/lvanderree/com.synplyworks.spider/blob/8585f6d6ba65749d1b9817f9cdec9df9241bc06e/src/clientManager.ts#L91(waarin de waarde nog een keer geforceerd naar Uppercase-first-letter wordt)
   Dit wordt ook in console gelogd.
   De client en clientmanager in src draaien ook zonder homey via node mocht je daar ervaren in zijn.

**Comment by lvanderree** [comment]
sorry voor de wat late reactie, maar ik heb helaas geen tijd om dit zo uit te zoeken.
Wat je nog wel zou kunnen proberen is om bij mijn.ithodaalderop.nl te kijken welke opties je daar ziet onder het klokprogramma bij de ventilator, want uiteindelijk roep ik diezelfde API aan, en heb ik binnen de homey app dezelfde mogelijkheden als die je daar ziet.

**Comment by AlfredG92** [comment]
Hoi Leon,
  
  
   
  
  
   Het lijkt erop nadat ik de Gateway heb verwijderd en opnieuw toegevoegd dat dit verholpen is.
  
  
   Toch bedankt voor je reactie.
  
  
   
  
  
   met vr. Groet,
  
  
   Alfred
  
  
   
    Op 27 maart 2020 11:21 schreef Leon van der Ree <notifications@github.com>:
   
   
    
   
   
    
   
   
   sorry voor de wat late reactie, maar ik heb helaas geen tijd om dit zo uit te zoeken.Wat je nog wel zou kunnen proberen is om bij mijn.ithodaalderop.nl te kijken welke opties je daar ziet onder het klokprogramma bij de ventilator, want uiteindelijk roep ik diezelfde API aan, en heb ik binnen de homey app dezelfde mogelijkheden als die je daar ziet.
