### ISSUE TITLE
Homey app no longer working

### ISSUE THREAD

**Issue by DeVisdude** [lvanderree/com.synplyworks.spider#13]

**Comment by DeVisdude** [comment]
I can no longer connect to itho with the homey app

**Comment by lvanderree** [comment]
Unfortunately just like the app from itho themselves... I am afraid their api is broken, although their website still works.

**Comment by DeVisdude** [comment]
The ios app from itho still works here. Also did a relogin to check.

**Comment by peternijssen** [comment]
See https://github.com/lvanderree/com.synplyworks.spider/issues/12 :)

**Comment by lvanderree** [comment]
fixed in version 0.6.2
