### ISSUE TITLE
Noting listed when trying to add a ventilation unit 

### ISSUE THREAD

**Issue by SlickF16** [lvanderree/com.synplyworks.spider#14]
Dear sir,

when trying to add an Itho Daalderop ventilation unit to my homey, the screen after logging into the spider app is empty. There is nothing to choose while in the actual app from spider I can control it all. Is there a fix for this issue?

Best regards,

Jeroen

**Comment by lvanderree** [comment]
Yesterday I've made a change that might solve your issue: 
https://homey.app/a/com.synplyworks.spider/test/

My guess is you probably have a ventilation unit without the spider thermostat, which now is supported as well

**Comment by SlickF16** [comment]
Sound great and indeed I have two ventilation units but no spider thermostat. When I try to add the ventilation unit, when it asks “select the device you would like to add” there is nothing to select.

What am I doing wrong?

Best regards,

Jeroen

Sent from my iPhone

On 10 May 2022, at 09:01, Leon van der Ree ***@***.***> wrote:

﻿

Yesterday I've made a change that might solve your issue:
https://homey.app/a/com.synplyworks.spider/test/

My guess is you probably have a ventilation unit without the spider thermostat, which now is supported as well
