### ISSUE TITLE
Werkt homey nog wel met de "ITHO DAALDEROP Centrale mechanische ventilatie CVE-S"?

### ISSUE THREAD

**Issue by beltesassar** [lvanderree/com.synplyworks.spider#18]
Dag Leon,

Ik heb  Homey Pro en ik oveweeg de "ITHO DAALDEROP Centrale mechanische ventilatie CVE-S" aan te schaffen. Ik heb dus geen Spider en ook geen account op Spider.
Graag wil ik weten of ik met Homey deze CVE-S kan aansturen mbv jouw applicatie in Homey.

Dank alvast voor je antwoord.

**Comment by lvanderree** [comment]
Hi,

Ik stuur de itho componenten aan via de api van itho, die op zijn beurt weer via de spider de signalen oppikt. Ik vermoed dus niet dat de CVE-S ook via deze api beschikbaar wordt.
