### ISSUE TITLE
New homey

### ISSUE THREAD

**Issue by Henbla56** [lvanderree/com.synplyworks.spider#19]
Do intend to adjust the spider app to the new homey pro (early 2023)?

**Comment by DeVisdude** [comment]
Hello, I am expecting my homey pro this week. Are you working on updating the app so it supports sdk3?
It would be really appreciated.

**Comment by lvanderree** [comment]
I was under the (false) impression, I had already done this...
I will take a look at it as soon as I can, shouldn't be too hard

**Comment by DeVisdude** [comment]
You rock!!

**Comment by lvanderree** [comment]
https://homey.app/a/com.synplyworks.spider/test/

**Comment by DeVisdude** [comment]
Great job! I immediately installed it on my old homey. Now I can plan to migrate to my new homey. Thanks!
And I left you a small donation on your paypal

**Comment by lvanderree** [comment]
merci, laat maar weten als je nog tegen iets aanloopt, voorlopig lijkt die het bij mij goed te doen
