### ISSUE TITLE
Update to Homey Pro 2023

### ISSUE THREAD

**Issue by bastiaanvanraaij** [lvanderree/com.synplyworks.spider#24]
Hello, will there be an update for the Homey Pro 2023??

**Comment by lvanderree** [comment]
see https://github.com/lvanderree/com.synplyworks.spider/issues/19#issuecomment-1471818463

**Comment by bastiaanvanraaij** [comment]
Ja zag het! Had hem al geïnstalleerd, maar via de normale weg kom je niet bij die test versie. Ben nog redelijk nieuw op dit gebied. Komt er nog een officiële versie? thnx voor antwoorden in ieder geval!

**Comment by lvanderree** [comment]
ben bang dat het niet veel zin heeft om er nog energie in te steken: zie https://github.com/lvanderree/com.synplyworks.spider/issues/23

Itho moet helaas de stekker trekken uit de gateway doordat fifthplay er mee gaat stoppen

**Comment by bastiaanvanraaij** [comment]
Maar goed dat ik niet zo'n thermostaat aangeschaft heb dan.. Ik heb al zo'n unit van nrgwatch thuis, maar het is mij te lastig om die te connecten.. Daar heb je toch wat meer ICT skills voor nodig. Ik zal #23 in de gaten houden. Succes!!
