### ISSUE TITLE
Werkt niet met Homey Pro early 2023

### ISSUE THREAD

**Issue by Gebru13** [lvanderree/com.synplyworks.spider#25]
Homey Pro gives a warning the app no longer is compatible with the latest Homey Pro. I would like to include our ventilator in flows, would you be so kind to upgrade the app please?

**Comment by lvanderree** [comment]
I'm sorry, but unfortunately the entire spider platform had been canceled: https://www.ithodaalderop.nl/additionelespiderproducten
