### ISSUE TITLE
spiderthermostaat niet te koppelen

### ISSUE THREAD

**Issue by johan9a** [lvanderree/com.synplyworks.spider#4]
goedendag

de ventilator is gekoppeld.
de spiderthermostaat kan ik niet koppelen.
als er gevraagd wordt om het apparaat te selecteren die je wilt toevoegen is er geen thermostaat zichtbaar

**Comment by lvanderree** [comment]
Heb je dit probleem nog met version 0.5, die nu in test staat?

**Comment by johan9a** [comment]
Goedeavond

Het werkt. Ik kan de thermostaten nu koppelen.
Goed werk. 👍

Handig zou ook zijn om het gas  en stroomverbruik uit te kunnen lezen

Vriendelijke groet,
Johan

Op do 21 jan. 2021 20:02 schreef Leon van der Ree <notifications@github.com

**Comment by lvanderree** [comment]
Mooi, goed te horen.

Uitlezen van de slimme meter staat op mijn todo list, maar die is wat vol, dus duurt wellicht nog even

**Comment by johan9a** [comment]
Geen probleem, ik kijk er naar uit,
Veel succes.

Op do 21 jan. 2021 20:18 schreef Leon van der Ree <notifications@github.com
