### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by nimbleconsulting** [lvanderree/com.synplyworks.spider#5]
When adding the fan:

![5F734869-A259-4512-BFAA-5D4FE4B23216](https://user-images.githubusercontent.com/42236633/114094994-3b88e400-98bd-11eb-9d53-864bddaba140.png)

**Comment by lvanderree** [comment]
Ik ben bang dat ik hier niet zoveel aan kan doen, en dat dit komt door de verbinding vanaf je gateway naar de api van itho-daalderop waar een hapering op zat. Ik vermoed dat wanneer je dit nog een keer probeert het wel zal werken.
