### ISSUE TITLE
Geen reactie 

### ISSUE THREAD

**Issue by Collin0209** [lvanderree/com.synplyworks.spider#8]
Speciaal de gateway aangeschaft, producten zichtbaar in de homey maar wat ik ook doe, de producten reageren nergens op. Wat doe ik fout?

**Comment by lvanderree** [comment]
Vreemd, als de producten zichtbaar zijn omgeeft homey succesvol in kunnen loggen bi dej itho gateway pm vervolgens de lijst op te kunnen halen, dan zou de aansturing ook moeten werken. Heb je niet tussentijds je wachtwoord op de gateway aangepast waardoor homey de lijst nog heeft onthouden met het oude wachtwoord?

**Comment by lvanderree** [comment]
En kan je via de itho website wel de instellingen wijzigen

**Comment by Collin0209** [comment]
Via de website en de app werken de handelingen wel. Ik heb de app opnieuw geïnstalleerd en de producten opnieuw toegevoegd. Toch werkt het niet… Ik ga nog wel even verder op onderzoek uit, mocht ik de oplossing gevonden hebben laat ik je het weten.

**Comment by Dkoster01** [comment]
Hallo Collin,

Is het je inmiddels gelukt het probleem op te lossen? Heb hier het zelfde probleem namelijk.

**Comment by lvanderree** [comment]
Ik ken zelf geen issues die open zouden staan. Alles hoort te werken, wel zijn er wel eens configuraties voorbij gekomen die verstorend werkten, maar aanpassen van config loste dit op en daarnaast heb ik de implementatie robuuster gemaakt door vreemde situaties beter af te handelen.

**Comment by Collin0209** [comment]
Goedenavond,

Bij mij heeft het geholpen de namen van de devices NIET aan te passen in de Homey app

**Comment by Dkoster01** [comment]
Vreemd. Als ik tijdens het toevoegen van het apparaat mijn login gegevens invul zou ik apparaten moeten zien welke ik zou kunnen toevoegen. Dit is en blijft leeg
<img width="511" alt="Schermafbeelding 2021-11-30 om 19 59 15" src="https://user-images.githubusercontent.com/71640090/144110737-a50200a9-88aa-4963-9cfb-c93369d1a7d7.png">
.

**Comment by lvanderree** [comment]
Ik heb vanavond geen tijd om gelijk verder te kijken, maar als je me https://github.com/lvanderree/com.synplyworks.spider/blob/master/app.json#L47 even een mailtje stuurt met je tel. dan kunnen we via chat een andere keer samen verder kijken.

**Comment by lvanderree** [comment]
Ik heb gisteren een update in test geplaatst waarmee ik dit probleem wellicht oplos
https://homey.app/a/com.synplyworks.spider/test/
